"""Word list for the Persian word guessing game.

Notes:
 - All words are common Persian (Farsi) vocabulary (nouns, verbs (stems / infinitives), adjectives, objects, animals, foods, places, abstract concepts, etc.).
 - No diacritics, no offensive or sensitive terms.
 - Single words only; no spaces, no punctuation.
 - You can randomly choose from WORDS for each round.
"""

# -*- coding: utf-8 -*-

WORDS = [
	# 1-50 (خوراکی ها و میوه ها)
    {"سیب": "A round fruit, usually red, green, or yellow, sweet or sour."},
    {"گلابی": "A soft fruit, green or yellow, shaped like a teardrop."},
    {"موز": "A long yellow fruit with soft sweet inside."},
    {"انار": "A round red fruit full of many small juicy seeds."},
    {"هلو": "A round soft fruit with fuzzy skin, usually orange or pink."},
    {"زردآلو": "A small orange fruit, sweet and juicy."},
    {"آلو": "A small round fruit, purple, red, or yellow, with a pit inside."},
    {"گیلاس": "A small round red fruit with a stem, sweet or sour."},
    {"آلبالو": "A small round red fruit, more sour than cherry."},
    {"خربزه": "A large oval fruit with yellow skin and sweet flesh."},
    {"طالبی": "A round melon with green or orange sweet flesh."},
    {"هندوانه": "A very large round fruit, green outside, red inside with black seeds."},
    {"کیوی": "A small brown fuzzy fruit with green juicy flesh inside."},
    {"انبه": "A tropical fruit, oval, yellow or orange, sweet and juicy."},
    {"پرتقال": "A round orange fruit with sweet or sour juicy flesh."},
    {"نارنگی": "A small orange fruit, easy to peel, sweet or sour."},
    {"لیمو": "A small oval yellow fruit, very sour."},
    {"لیموترش": "A green or yellow small fruit, very sour, like lemon."},
    {"لیموشیرین": "A small yellow fruit, looks like lemon but tastes sweet."},
    {"گریپفروت": "A large round citrus fruit, yellow or pink, bitter-sour taste."},
    {"آناناس": "A tropical fruit with spiky skin and sweet yellow inside."},
    {"توت": "A small soft fruit, white, red, or black, sweet taste."},
    {"شاهتوت": "A dark purple fruit, looks like a long berry, sweet-sour taste."},
    {"تمشک": "A small red or black berry, soft and sweet-sour."},
    {"خرما": "A brown oval fruit, very sweet, grows on palm trees."},
    {"کشمش": "A small dried grape, sweet and chewy."},
    {"زیتون": "A small green or black fruit, bitter or salty, often pickled."},
    {"بادام": "A small oval nut with hard shell, eaten dry or roasted."},
    {"پسته": "A small green nut with hard beige shell."},
    {"فندق": "A small round nut with hard brown shell."},
    {"گردو": "A large nut with hard wrinkled shell, inside is brain-shaped."},
    {"کنجد": "Very tiny seeds, white or black, used on bread and sweets."},
    {"نخود": "A small round beige legume, used in stews and hummus."},
    {"عدس": "Very small round flat legume, green, brown, or red."},
    {"لوبیا": "A medium-sized legume, red, black, or white, used in food."},
    {"برنج": "Small long white grains, main food when cooked."},
    {"نان": "Flat or fluffy baked food made from flour."},
    {"ماست": "A white dairy food, creamy, sour taste."},
    {"دوغ": "A white drink made from yogurt, salty and sour."},
    {"پنیر": "A dairy food, white or yellow, salty or creamy."},
    {"کره": "A yellow dairy product, soft and oily."},
    {"عسل": "A thick golden sweet liquid made by bees."},
    {"شکر": "Small white crystals, very sweet."},
    {"قند": "Small white sugar cubes, sweet, used in tea."},
    {"زعفران": "Thin red threads, expensive spice, yellow color when cooked."},
    {"دارچین": "A brown spice from tree bark, strong sweet smell."},
    {"فلفل": "A spice, black, white, or red, makes food hot or spicy."},
    {"نمک": "Small white crystals, salty taste, basic seasoning."},
    {"زیره": "Small brown seeds, strong aroma, used as spice."},
    
	# 51-100 (سبزیجات و خوراک)
    {"قارچ": "A small edible fungus, soft, usually white or brown, used in cooking."},
    {"کاهو": "A leafy green vegetable, light and crunchy, often used in salads."},
    {"کلم": "A round leafy vegetable, usually green or white, dense leaves."},
    {"خیار": "A long green vegetable, crunchy, with watery flesh."},
    {"گوجه": "A round red vegetable or fruit, juicy, used in salads and cooking."},
    {"پیاز": "A round bulb vegetable, white, yellow, or red, with strong smell."},
    {"سیر": "A small bulb with cloves, white, strong smell and taste."},
    {"هویج": "A long orange root vegetable, crunchy and sweet."},
    {"شلغم": "A round root vegetable, white or purple outside, white inside."},
    {"بادمجان": "A long or oval purple vegetable, smooth skin, soft inside."},
    {"کدو": "A long light green vegetable, soft inside, mild taste."},
    {"تره": "A long thin green leafy herb, used fresh in food."},
    {"جعفری": "A small green herb with curly or flat leaves, strong smell."},
    {"گشنیز": "A green herb with small leaves, strong and fresh smell."},
    {"ریحان": "A green herb with smooth leaves, sweet smell."},
    {"نعناع": "A green herb with pointed leaves, cool fresh smell."},
    {"شوید": "A green herb with thin needle-like leaves, strong smell."},
    {"اسفناج": "A leafy green vegetable, soft dark leaves, used in cooking."},
    {"بامیه": "A green ridged vegetable, small and finger-shaped, sticky inside."},
    {"کرفس": "A crunchy green stalk vegetable, with leaves, fresh taste."},
    {"زنجبیل": "A brown root, irregular shape, spicy taste."},
    {"چای": "A hot drink made from dried leaves, usually black or green."},
    {"قهوه": "A hot drink made from roasted beans, dark and bitter."},
    {"شیر": "A white liquid drink from animals, smooth and creamy."},
    {"خامه": "A thick white dairy product, soft and creamy."},
    {"ماکارونی": "A pasta made from wheat, long or short shapes, yellowish."},
    {"سوپ": "A hot liquid food, made with vegetables, meat, or grains."},
    {"کباب": "Grilled meat, cooked on skewers or fire."},
    {"جوجه": "Grilled chicken pieces, usually on skewers."},
    {"بره": "Lamb meat, tender, used roasted or grilled."},
    {"گوشت": "Meat from animals, red or white, used in cooking."},
    {"مرغ": "Chicken meat, white or light brown, used widely in cooking."},
    {"ماهی": "Fish, lives in water, edible meat with scales."},
    {"سوسیس": "A processed meat, cylindrical shape, cooked or fried."},
    {"کالباس": "A processed meat, sliced, usually pink or red."},
    {"سالاد": "A dish made from mixed raw vegetables, sometimes with dressing."},
    {"کوفته": "Meatballs, round, made of meat and rice."},
    {"کشک": "A thick dairy product, white, salty, used in Persian dishes."},

	# 101-150 (حیوانات)
    {"گربه": "A small furry pet, lives in houses, meows, has whiskers."},
    {"سگ": "A loyal furry pet, barks, guards houses, many breeds."},
    {"اسب": "A large four-legged animal, rides by humans, runs fast."},
    {"گاو": "A big farm animal, gives milk, has horns, eats grass."},
    {"گوسفند": "A farm animal with wool, gives meat and milk."},
    {"بره": "A young sheep, small and cute, has soft wool."},
    {"بز": "A farm animal, climbs rocks, has horns, gives milk."},
    {"خر": "A strong farm animal, carries loads, has long ears."},
    {"شتر": "A desert animal with humps, carries loads, long legs."},
    {"شیر": "A large wild cat, king of jungle, golden mane."},
    {"ببر": "A big wild cat, orange with black stripes."},
    {"پلنگ": "A wild spotted cat, fast climber, hunts in forests."},
    {"گرگ": "A wild dog-like animal, howls, hunts in packs."},
    {"روباه": "A small wild animal, red fur, bushy tail, clever."},
    {"خرس": "A big wild animal, furry, strong, eats fish and honey."},
    {"خرگوش": "A small animal, long ears, hops, eats carrots."},
    {"موش": "A tiny rodent, gray, long tail, lives in houses."},
    {"لاکپشت": "A slow reptile, hard shell, lives on land."},
    {"مار": "A reptile, no legs, long body, some are venomous."},
    {"مارمولک": "A small reptile, four legs, climbs walls."},
    {"قورباغه": "A small green animal, jumps, lives near water, croaks."},
    {"نهنگ": "A giant sea mammal, breathes air, lives in oceans."},
    {"دلفین": "A friendly sea mammal, smart, jumps from water."},
    {"کوسه": "A large sea fish, sharp teeth, predator."},
    {"اختاپوس": "A sea animal with 8 arms, soft body, squirts ink."},
    {"کرم": "A small soft animal, no legs, lives in soil."},
    {"زنبور": "A small flying insect, makes honey, has a sting."},
    {"مورچه": "A tiny insect, lives in colonies, carries food."},
    {"ملخ": "A jumping insect, green, eats plants, makes sound."},
    {"پروانه": "A flying insect with colorful wings, comes from a cocoon."},
    {"سنجاقک": "A flying insect, long body, transparent wings."},
    {"کفشدوزک": "A small round insect, red with black spots."},
    {"عنکبوت": "An insect-like animal, 8 legs, makes webs."},
    {"عقرب": "A desert animal, 8 legs, stinger tail, venomous."},
    {"پرستو": "A small bird, flies fast, forked tail."},
    {"کلاغ": "A black bird, smart, loud cawing sound."},
    {"گنجشک": "A small brown bird, common in cities, chirps."},
    {"کبوتر": "A city bird, gray, coos, often kept in flocks."},
    {"طاووس": "A large bird, colorful feathers, spreads a big tail."},
    {"عقاب": "A huge bird of prey, strong beak, sharp claws."},
    {"باز": "A hunting bird, fast flyer, used in falconry."},
    {"شاهین": "A bird of prey, very fast, sharp eyesight."},
    {"قو": "A large white bird, long neck, swims gracefully."},
    {"اردک": "A farm bird, short neck, swims in ponds."},
    {"غاز": "A large farm bird, long neck, honks loudly."},
    {"مرغابی": "A wild duck, swims in lakes and rivers."},
    {"بوقلمون": "A big farm bird, fan tail, eaten at feasts."},

	# 151-200 (حشرات و پرندگان بیشتر + دریا)
    {"فلامینگو": "A tall bird with long legs, often pink, standing in water."},
    {"بلدرچین": "A small ground bird, brown spotted feathers, known for eggs."},
    {"دارکوب": "A bird that pecks trees with its strong beak, often black and red."},
    {"بلبل": "A small songbird, brownish, famous for melodious singing."},
    {"هما": "A large bird of prey from mountains, associated with good luck."},
    {"پنگوئن": "A black and white bird, cannot fly, walks on ice, swims well."},
    {"خفاش": "A flying mammal with wings, active at night."},
    {"زنبورعسل": "A small insect, yellow and black, makes honey."},
    {"صدف": "A sea creature with a hard shell, sometimes has a pearl."},
    {"میگو": "A small sea animal, pink when cooked, many legs."},
    {"خرچنگ": "A sea creature with hard shell, two claws, walks sideways."},
    {"حلزون": "A small soft animal with spiral shell, moves slowly."},
    {"کرگردن": "A huge gray animal, thick skin, has one or two horns."},
    {"فیل": "A giant gray animal, long trunk, big ears, tusks."},
    {"گورخر": "An animal like a horse, black and white stripes."},
    {"شغال": "A wild dog-like animal, yellow-brown, howls at night."},
    {"کفتار": "A strong wild animal, laughs loudly, scavenger."},
    {"راسو": "A small mammal, long body, can spray bad smell."},
    {"سمور": "A small furry animal, swims well, playful."},
    {"گراز": "A wild pig, strong tusks, lives in forests."},
    {"آهو": "A graceful animal, slender body, fast runner, antlers small."},
    {"گوزن": "A large deer, branching antlers, lives in herds."},
    {"بزکوهی": "A mountain goat, climbs steep rocks, strong horns."},
    {"قوچ": "A male sheep, curly horns, strong body."},
    {"لاما": "A tall animal with long neck, used as pack animal in Andes."},
    {"کوالا": "A small gray animal, climbs eucalyptus trees, eats leaves."},
    {"کانگورو": "A large animal with strong legs, jumps, carries baby in pouch."},
    {"پاندا": "A big bear, black and white, eats bamboo."},
    {"چیتا": "A spotted big cat, fastest land animal."},
    {"لکلک": "A tall bird, long legs and beak, nests on rooftops."},

	# 201-250 (اشیاء روزمره)
    {"کتاب": "A rectangular object made of paper, used for reading."},
    {"دفتر": "A paper booklet with blank pages, used for writing notes."},
    {"مداد": "A thin wooden stick with graphite inside, used for writing or drawing."},
    {"خودکار": "A plastic or metal pen with ink inside, used for writing."},
    {"پاککن": "A small rubber object, used to remove pencil marks."},
    {"خطکش": "A flat straight tool, usually plastic or metal, used for measuring or drawing lines."},
    {"قیچی": "A metal tool with two blades, used for cutting paper or fabric."},
    {"گیره": "A small metal or plastic clip, used to hold papers together."},
    {"کاغذ": "A thin white sheet, used for writing or printing."},
    {"پرگار": "A metal tool with two arms, one sharp and one with a pencil, used for drawing circles."},
    {"گوشی": "A small handheld electronic device, used for calling and apps."},
    {"تبلت": "A flat handheld electronic screen, larger than a phone, smaller than a laptop."},
    {"هدفون": "A pair of small speakers worn on the head or in ears, used for listening to sound."},
    {"موس": "A small handheld device, used to move a pointer on a computer screen."},
    {"نمایشگر": "A flat electronic screen, used for showing images or videos."},
    {"تلویزیون": "A large electronic screen, usually in living rooms, for watching programs."},
    {"دوربین": "A handheld device with a lens, used for taking pictures or videos."},
    {"لنز": "A small transparent glass or plastic piece, used in cameras or glasses."},
    {"کیف": "A small bag, usually carried by hand, for holding items."},
    {"کوله": "A large bag with two straps, carried on the back."},
    {"عینک": "A frame with two glass lenses, worn on the face to help see."},
    {"ساعت": "A small device worn on the wrist or wall, used to tell time."},
    {"کمربند": "A long strap of leather or fabric, worn around the waist."},
    {"کلاه": "An item of clothing worn on the head, often made of fabric."},
    {"دستکش": "A clothing item worn on the hands, usually fabric or leather."},
    {"کفش": "A pair of items worn on the feet, usually made of leather or fabric."},
    {"پیراهن": "A clothing item with sleeves and buttons, worn on the upper body."},
    {"شلوار": "A clothing item with two legs, worn on the lower body."},
    {"کت": "A short formal jacket, usually worn over a shirt."},
    {"کاپشن": "A warm padded jacket, often with a hood, for cold weather."},
    {"پالتو": "A long warm coat, worn in winter."},
    {"جوراب": "A piece of clothing worn on the feet, usually made of fabric."},
    {"کراوات": "A long strip of fabric tied around the neck, worn with shirts."},
    {"شال": "A long piece of fabric, wrapped around the neck or shoulders."},
    {"روسری": "A piece of fabric, worn on the head, covering hair."},
    {"چتر": "A foldable fabric canopy on a stick, used for protection from rain."},
    {"چاقو": "A metal tool with a sharp blade, used for cutting food."},
    {"قاشق": "A small rounded metal utensil, used for eating soup or rice."},
    {"چنگال": "A metal utensil with pointed prongs, used for eating solid food."},
    {"بشقاب": "A flat round dish, used for serving food."},
    {"لیوان": "A cylindrical container, used for drinking water or juice."},
    {"فنجان": "A small cup with a handle, used for drinking tea or coffee."},
    {"کتری": "A metal container, used to boil water on a stove."},
    {"قوری": "A container with a spout, used for making and serving tea."},
    {"ماهیتابه": "A flat metal pan with a handle, used for frying food."},

	# 251-300 (خانه و لوازم)
    {"قابلمه": "A metal pot used for cooking on heat."},
    {"اجاق": "A kitchen stove, usually metal, used for cooking."},
    {"یخچال": "A large cold appliance to store food, usually white and box-shaped."},
    {"فریزر": "A very cold appliance to freeze food, box-shaped."},
    {"جاروبرقی": "An electric vacuum cleaner for cleaning floors."}, #
    {"جارودستی": "A manual broom for sweeping floors."}, #
    {"گاز": "A gas stove with burners for cooking."},
    {"بخاری": "A heater that produces warmth indoors."},
    {"شومینه": "A fireplace built into a wall, used for heat or fire."},
    {"کولر": "An air cooler or air conditioner for cooling rooms."},
    {"پنکه": "A fan with rotating blades to move air."},
    {"چراغ": "A lamp or light source for brightness."},
    {"لامپ": "A light bulb, small glass object giving light."},
    {"پنجره": "A glass opening in the wall to see outside."},
    {"دیوار": "A solid wall that separates spaces."},
    {"سقف": "A ceiling or roof over a room."},
    {"آینه": "A mirror with glass surface reflecting images."},
    {"فرش": "A carpet or rug placed on the floor."},
    {"قالی": "A traditional woven carpet covering the floor."},
    {"موکت": "A wall-to-wall floor carpet covering."},
    {"پرده": "Curtains or drapes hung over windows."},
    {"مبل": "A sofa, soft furniture for sitting."},
    {"صندلی": "A chair for one person to sit."},
    {"میز": "A table with a flat surface for placing things."},
    {"کمد": "A wardrobe or cupboard for storing clothes or items."},
    {"کتابخانه": "A bookshelf or bookcase for keeping books."},
    {"قفسه": "A shelf or rack to store objects."},
    {"تخت": "A bed for sleeping."},
    {"بالش": "A pillow, soft object for resting the head."},
    {"تشک": "A mattress, large cushion for sleeping on."},
    {"پتو": "A blanket for covering while sleeping."},
    {"کلید": "A key, small metal object for opening locks."},
    {"قفل": "A lock, metal device to secure doors or items."},
    {"نردبان": "A ladder used for climbing up and down."},
    {"چکش": "A hammer, hand tool with a heavy head."},
    {"میخ": "A nail, small metal rod for fastening things."},
    {"پیچ": "A screw, small metal fastener with threads."},
    {"انبردست": "Pliers, a hand tool for gripping objects."},
    {"اره": "A saw, tool with a sharp blade for cutting wood."},
    {"آچار": "A wrench, hand tool for turning nuts and bolts."},
    {"متر": "A measuring tape for length."},

	# 301-350 (مکان ها)
    {"خانه": "A place where people live, usually small, has rooms and furniture."},
    {"آپارتمان": "A set of rooms in a tall building where families live."},
    {"ویلا": "A large house, often with a garden, outside the city."},
    {"مدرسه": "A place where children study, with classrooms and a yard."},
    {"دانشگاه": "A big place for higher education, many buildings and students."},
    {"کتابخانه": "A building with many books where people read or borrow them."},
    {"بیمارستان": "A large building where sick people are treated by doctors."},
    {"داروخانه": "A shop where people buy medicine."},
    {"بانک": "A place where people keep money and do financial work."},
    {"کارخانه": "A large building where products are made by machines or workers."},
    {"فروشگاه": "A shop where people buy different items."},
    {"بازار": "A large area with many shops close together."},
    {"نانوایی": "A small shop where bread is baked and sold."},
    {"قنادی": "A shop where cakes and sweets are sold."},
    {"رستوران": "A place where people sit and eat meals."},
    {"کافه": "A small place for drinks, snacks, and sitting."},
    {"پارک": "An outdoor green area with trees, benches, and paths."},
    {"باغ": "A green place with many plants, trees, or flowers."},
    {"موزه": "A building where old or valuable objects are shown."},
    {"سینما": "A building where people watch movies on a big screen."},
    {"فرودگاه": "A very large place where airplanes land and take off."},
    {"ایستگاه": "A place where buses or trains stop for passengers."},
    {"مترو": "An underground train station for city transport."},
    {"ترمینال": "A big station where long-distance buses arrive and leave."},
    {"بندر": "A coastal area where ships load and unload cargo."},
    {"اسکله": "A platform near water where boats tie up."},
    {"هتل": "A large building where people pay to stay overnight."},
    {"مسجد": "A religious building where Muslims pray."},
    {"کلیسا": "A religious building where Christians pray."},
    {"پلیس": "A station where officers work to keep law and order."},
    {"دادگاه": "A building where legal cases and trials are held."},
    {"گالری": "A building or room where artworks are shown."},
    {"کارگاه": "A small place where workers make or repair things."},
    {"آزمایشگاه": "A room where experiments and scientific tests are done."},
    {"گلخانه": "A glass building where plants grow with controlled climate."},
    {"کارواش": "A place where cars are washed."},
    {"استادیوم": "A very large outdoor place for sports and many spectators."},
    {"باشگاه": "A building for sports, exercise, or fitness activities."},
    {"زمین": "An open flat area, often used for farming or games."},
    {"ساختمان": "A general structure with walls and a roof."},
    {"برج": "A very tall building, often with many floors."},
    {"کوچه": "A narrow passage between houses, smaller than a street."},
    {"خیابان": "A wide road in the city with cars and buildings."},
    {"بزرگراه": "A very wide road where cars move fast between cities."},

	# 351-400 (فصول، طبیعت، جغرافیا)
    {"بهار": "Spring, a warm season with flowers and green nature"},
    {"تابستان": "Summer, a hot season with strong sun"},
    {"پاییز": "Autumn, a cool season with falling leaves"},
    {"زمستان": "Winter, a cold season with snow and ice"},
    {"باران": "Rain, water falling from the sky"},
    {"برف": "Snow, white frozen water falling from the sky"},
    {"یخ": "Ice, frozen solid water, cold and hard"},
    {"تگرگ": "Hail, hard ice balls falling from the sky"},
    {"رعد": "Thunder, loud sound after lightning"},
    {"برق": "Lightning, bright flash in the sky during storm"},
    {"طوفان": "Storm, very strong wind and heavy rain"},
    {"باد": "Wind, moving air you can feel"},
    {"خورشید": "Sun, bright hot star in the sky"},
    {"ماه": "Moon, round object seen in the night sky"},
    {"ستاره": "Star, shining point of light in the night sky"},
    {"ابر": "Cloud, white or gray mass in the sky"},
    {"آسمان": "Sky, space above the ground, blue in day"},
    {"رودخانه": "River, long flowing water on land"},
    {"دریا": "Sea, large body of salty water"},
    {"دریاچه": "Lake, large body of still water inland"},
    {"برکه": "Pond, small body of still water"},
    {"چشمه": "Spring, natural water coming from the ground"},
    {"آبشار": "Waterfall, water falling from high to low"},
    {"جزیره": "Island, land surrounded by water"},
    {"کوه": "Mountain, very high land with peaks"},
    {"قله": "Peak, the top of a mountain"},
    {"دشت": "Plain, wide flat open land"},
    {"بیابان": "Desert, dry hot land with little water"},
    {"تپه": "Hill, small raised land, lower than mountain"},
    {"جنگل": "Forest, large area full of trees"},
    {"چمن": "Grass, green plant covering the ground"},
    {"گل": "Flower, colorful plant with petals"},
    {"درخت": "Tree, tall plant with trunk and branches"},
    {"بوته": "Bush, small plant with many branches"},
    {"شاخه": "Branch, part of a tree growing from trunk"},
    {"برگ": "Leaf, flat green part of a plant"},
    {"صخره": "Cliff, large steep rock face"},
    {"سنگ": "Stone, small hard piece of rock"},
    {"ماسه": "Sand, tiny grains near sea or desert"},
    {"خاک": "Soil, soft earth where plants grow"},
    {"زمین": "Land, ground where we stand"},
    {"اقیانوس": "Ocean, very large salty water body"},
    {"ساحل": "Beach, sandy land beside the sea"},

	# 401-450 (رنگ ها، شکل ها، عدد ها)
    {"قرمز": "A primary color, often seen on apples, blood, or stop signs"},
    {"آبی": "A primary color, seen in the sky and sea"},
    {"سبز": "A color, common in grass and trees"},
    {"زرد": "A bright color, seen in the sun and bananas"},
    {"نارنجی": "A color, mix of red and yellow, like an orange fruit"},
    {"بنفش": "A color, mix of red and blue, like lavender flowers"},
    {"صورتی": "A light red color, often linked to roses and candy"},
    {"مشکی": "A dark color, seen in night or coal"},
    {"سفید": "A bright color, seen in snow and milk"},
    {"خاکستری": "A neutral color, mix of black and white, like ash"},
    {"زرین": "A shiny golden color, like jewelry or coins"},
    {"لاجوردی": "A deep blue color, like lapis lazuli stone"},
    {"یشمی": "A greenish stone color, like jade"},
    {"ارغوانی": "A deep purple-red color, like wine"},
    {"زعفرانی": "A yellow-orange color, like saffron spice"},
    {"گلبهی": "A soft pink-red color, like rose petals"},
    {"دایره": "A round shape, no corners or edges"},
    {"مربع": "A shape with four equal sides and right angles"},
    {"مستطیل": "A shape with four sides, opposite sides equal"},
    {"مثلث": "A shape with three sides and three angles"},
    {"بیضی": "An oval shape, like an egg"},
    {"ذوزنقه": "A four-sided shape with one pair of parallel sides"},
    {"کره": "A 3D round shape, like a ball or the Earth"},
    {"مکعب": "A 3D shape with six equal square faces, like dice"},
    {"استوانه": "A 3D shape with two circular bases, like a can"},
    {"مخروط": "A 3D shape with a circular base and a point, like an ice cream cone"},
    {"هرم": "A 3D shape with a polygon base and triangular sides, like Egyptian pyramids"},
    {"یک": "The number 1, a single unit"},
    {"دو": "The number 2, a pair"},
    {"سه": "The number 3, a trio"},
    {"چهار": "The number 4, a square count"},
    {"پنج": "The number 5, a hand’s fingers"},
    {"شش": "The number 6, common in dice"},
    {"هفت": "The number 7, days in a week"},
    {"هشت": "The number 8, an even number"},
    {"نه": "The number 9, just before ten"},
    {"ده": "The number 10, base of decimal system"},

	# 451-500 (مفاهیم عمومی)
    {"روز": "Part of a day, when the sun is up, opposite of night"},
    {"شب": "Part of a day, dark time when the sun is down"},
    {"صبح": "Beginning of the day, after night, before noon"},
    {"ظهر": "Middle of the day, when the sun is highest"},
    {"عصر": "Late part of the day, before sunset"},
    {"غروب": "Time when the sun sets, transition to night"},
    {"ترس": "Negative feeling of danger or threat"},
    {"عشق": "Strong positive emotion of affection"},
    {"نفرت": "Strong negative emotion, opposite of love"},
    {"آرامش": "State of peace and calm"},
    {"خشم": "Strong negative emotion of anger"},
    {"شادی": "Feeling of happiness"},
    {"غم": "Sad emotional state, opposite of joy"},
	{"جنگ": "Conflict between groups or countries"},
 
	# 501-550 (مشاغل)
    {"پزشک": "A person who works in a hospital or clinic, wears a white coat, and treats sick people."},
    {"پرستار": "A person in a hospital who helps patients, often wears a uniform and assists doctors."},
    {"مهندس": "A person who designs or builds things, often works with plans, machines, or buildings."},
    {"معلم": "A person who teaches students in a school classroom."},
    {"استاد": "A person who teaches at a university and gives lectures."},
    {"دانشجو": "A person who studies at a university and attends classes."},
    {"کارگر": "A person who does physical work, often with tools or in construction."},
    {"کشاورز": "A person who grows plants or raises animals on a farm."},
    {"راننده": "A person who drives a vehicle like a bus, taxi, or truck."},
    {"خلبان": "A person who flies an airplane, wears a uniform, and works in the sky."},
    {"نجار": "A person who makes or repairs things from wood."},
    {"آهنگر": "A person who works with metal, shaping it using fire and tools."},
    {"نقاش": "A person who paints walls, houses, or pictures."},
    {"بنا": "A person who builds walls and buildings using bricks or stones."},
    {"برقکار": "A person who installs or repairs electrical wires and systems."},
    {"طراح": "A person who creates plans, drawings, or looks for objects or clothes."},
    {"نویسنده": "A person who writes books, stories, or articles."},
    {"شاعر": "A person who writes poems and uses artistic language."},
    {"خبرنگار": "A person who gathers and reports news for media."},
    {"عکاس": "A person who takes pictures with a camera."},
    {"بازیگر": "A person who performs in movies, TV, or theater."},
    {"کارگردان": "A person who leads actors and crew in making films or plays."},
    {"مترجم": "A person who changes spoken or written words from one language to another."},
    {"وکیل": "A person who defends or advises people in legal matters."},
    {"قاضی": "A person in a court who decides right or wrong and gives judgment."},
    {"مدیر": "A person who leads or manages a company, office, or team."},
    {"فروشنده": "A person who sells goods in a store or market."},
    {"قصاب": "A person who cuts and sells meat in a shop."},
    {"نانوا": "A person who makes bread in a bakery."},
    {"آشپز": "A person who cooks food in a kitchen or restaurant."},
    {"پیک": "A person who delivers packages or food using a bike, motor, or car."},
    {"مکانیک": "A person who repairs cars or machines."},
    {"داروساز": "A person who prepares and gives medicine in a pharmacy."},
    {"کتابدار": "A person who organizes and lends books in a library."},
    {"مجری": "A person who presents TV or radio programs."},
    {"گوینده": "A person who speaks news or content on TV or radio."},]

	## 701-750 (ورزش و حرکات)
	# "فوتبال", "والیبال", "بسکتبال", "هندبال", "شنا", "دوچرخه", "کوهنوردی", "دوی", "بوکس", "کاراته",
	# "جودو", "تکواندو", "کیکبوکس", "یوگا", "پیلاتس", "بدنسازی", "ژیمناستیک", "تنیس", "پینگپنگ", "شطرنج",
	# "بولینگ", "هاکی", "اسکی", "برفالغ", "اسنوبرد", "موجسواری", "قایقرانی", "روئینگ", "پاروزنی", "کوچینگ",
	# "تیراندازی", "شمشیربازی", "سوارکاری", "دوچرخهسواری", "ورزش", "تمرین", "کشیدگی", "پرش", "چرخش", "لغزش",
	# "تعادل", "قدرت", "سرعت", "انعطاف", "استقامت", "نفس", "عرق", "پیروزی", "شکستورزشی", "داور",

	# # 751-800 (احساسات و حالات)
	# "ترس", "شجاعت", "خجالت", "غرور", "حسرت", "ناراحتی", "نگرانی", "دلهره", "اضطراب", "هیجان",
	# "عجله", "حوصله", "بیحوصلگی", "کنجکاوی", "گناه", "بخشش", "آزادی", "استرس", "آرامشذهن", "غمناک",
	# "نشاط", "رضایت", "سرافرازی", "شرم", "کینه", "دلگرمی", "دلسردی", "بیتفاوتی", "حیرت", "شگفتی",
	# "الهام", "تمرکز", "حواسپرتی", "اعتمادبنفس", "بیاعتمادی", "صداقتدرونی", "خلوص", "دلسوزی", "حساسیت", "لطافت",
	# "محبت", "عشقپاک", "نومیدی", "امیدواری", "رنج", "تسکین", "آشتی", "جنگ", "صلح", "وفاق",

	# # 801-850 (مفاهیم و علمی ساده)
	# "اتم", "مولکول", "سلول", "بافت", "اندام", "ژن", "نور", "صدا", "انرژی", "ماده",
	# "جرم", "حجم", "چگالی", "دما", "فشار", "سرعت", "شتاب", "نیرو", "کار", "قدرت",
	# "میدان", "موج", "ذره", "الکترون", "پروتون", "نوترون", "واژه", "جمله", "عبارت", "متن",
	# "عدد", "معادله", "فرمول", "محاسبه", "آزمایش", "نظریه", "مدل", "نمودار", "منحنیعلمی", "داده",
	# "آمار", "میانگین", "میانه", "واریانس", "احتمال", "منطق", "برهان", "قضیه", "فرضیه", "نتیجه",

	# # 851-900 (حمل و نقل)
	# "ماشین", "اتومبیل", "دوچرخ", "موتور", "کامیون", "اتوبوس", "مینیبوس", "قطار", "مترو", "تراموا",
	# "هواپیما", "بالگرد", "هلیکوپتر", "کشتی", "قایق", "زیردریایی", "تاکسی", "وانت", "تریلر", "اسکوتر",
	# "دوچرخهبرقی", "موتورسیکلت", "چیندهنوا", "ریل", "چرخ", "صندلیراننده", "فرمان", "ترمز", "پدال", "کمربندایمنی",
	# "چراغقرمز", "تقاطع", "علائم", "تابلو", "مسیر", "نقشه", "ناوبر", "سوخت", "بنزین", "گازوئیل",
	# "پارکینگ", "گاراژ", "جاده", "پیادهرو", "پل", "تونل", "بلیت", "سفر", "مسافر", "راننده",

	# # 901-950 (طبیعت بیشتر و هواشناسی)
	# "رطوبت", "خشکی", "مه", "غبار", "دود", "آلودگی", "دماوند", "زمینلرزه", "زلزله", "آتشفشان",
	# "گدازه", "لایه", "پوسته", "هسته", "اقلیم", "آبوهوا", "پیشبینی", "هواشناسی", "شاخص", "فصلبارانی",
	# "کویر", "سراب", "چاه", "کانال", "سد", "دریابزرگ", "خلیج", "تنگه", "دریاکوچک", "نیزار",
	# "باتلاق", "جنگلبارانی", "دره", "کانیون", "دلتا", "دریاکف", "معدن", "منبع", "چشمهآبگرم", "یخچالطبیعی",
	# "قطب", "شفق", "برفک", "مهتاب", "خورشیدگرفتگی", "ماهگرفتگی", "ستارهقطبی", "افق", "نیمکره", "مدار",

	# # 951-1000 (واژگان تکمیلی متنوع)
	# "فرصت", "چالش", "پاسخ", "سوال", "مساله", "راهحل", "تصمیم", "انتخاب", "اولویت", "برنامه",
	# "پیشرفت", "پایه", "ساختار", "نظام", "روش", "الگو", "کاربرد", "ابزار", "تحلیل", "طراحی",
	# "اجرا", "بازخورد", "کیفیت", "کمیت", "منبع", "هدفگذاری", "ارزش", "ارزیابی", "بهبود", "نگرش",
	# "رفتار", "قانون", "قانونگذاری", "نظم", "اخلاق", "مسئولیت", "اعلان", "اطلاع", "گزارش", "خبر",
	# "نکته", "خلاصه", "نتیجه گیری", "مقدمه", "فهرست", "صفحهآرایی", "پژوهش", "بررسی", "کاوش", "کشف",


def get_random_word(rng=None):
	"""Return a random word from the list.

	Parameters
	----------
	rng : random.Random | None
		Optional random number generator (for test determinism).
	"""
	import random
	r = rng if rng is not None else random
	word, description = list(r.choice(WORDS).items())[0]
	return (word, description)

get_random_word()
